services:
  - docker

branches:
  only:
    - master

before_install:
  - docker build -t hello-world .
  - docker run -d -p 127.0.0.1:3000:3000 hello-world

script:
  - docker ps | grep hello-world
  - curl --fail localhost:3000
  - curl --fail -I localhost:3000
